'use client';

import { supabase } from '@/app/lib/supabase';
import React, { useState } from 'react';
// ⚠️ 기존 프로젝트의 supabaseClient가 위치한 경로로 매칭해주세요.
import Image from "next/image";
import Link from "next/link";

export default function InfluencerApplyPage() {
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    snsChannel: '',
    referralCode: '',
  });
  const [isAgreed, setIsAgreed] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false); // [추가] 등록 중 로딩 상태 관리

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    
    if (name === 'phone') {
      const onlyNumbers = value.replace(/[^0-9]/g, '');
      setFormData({ ...formData, [name]: onlyNumbers });
    } else if (name === 'referralCode') {
      const cleanCode = value.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
      setFormData({ ...formData, [name]: cleanCode });
    } else {
      setFormData({ ...formData, [name]: value });
    }
  };

  // 선점 및 유보를 위한 프리미엄 금지 단어 목록 (모두 대문자로 작성)
  const PREMIUM_BLACKLIST = [
    'LOVE', 'APPLE', 'GOODS', 'SHOP', 'ADMIN', 
    'STAR', 'KING', 'QUEEN', 'SUPER', 'HYPER', 'MEGA',
    'KOREA', 'SEOUL', 'GIFT', 'EVENT', 'FREE', 'BONUS',
    'ABLE','ACID','ACNE','ACRE','ACTS','AGED','AIDE','AIRY','AJAR','AKIN','ALTO','AMEN','AMID','ANEW','ANTE','ARCH','AREA','ARIA','ARMY','ASHY','ATOM','AUNT','AURA','AUTO','AXIS','BABY','BACK','BAIT','BAKE','BALD','BALE','BALL','BAND','BANK','BARE','BARK','BASE','BASS','BATH','BEAK','BEAM','BEAN','BEAR','BEAT','BEEF','BEEN','BEER','BELL','BELT','BEND','BENT','BEST','BETA','BIAS','BIKE','BILL','BIND','BIRD','BITE','BLUE','BOAR','BOAT','BODY','BOLD','BOLT','BOMB','BOND','BONE','BOOK','BOOM','BOOT','BORN','BOSS','BOTH','BOWL','BULB','BULK','BULL','BUMP','BURN','BURST','BUSH','BUSY','BYTE','CAFE','CAGE','CAKE','CALM','CAMP','CARD','CARE','CART','CASE','CASH','CAST','CAVE','CELL','CENT','CHAT','CHEF','CHEW','CHIP','CITY','CLAN','CLAY','CLIP','CLUB','COAL','COAT','CODE','COIN','COLD','COLA','COMB','COOK','COOL','COOP','COPY','CORE','CORN','COST','COVE','CRAB','CREW','CROP','CROW','CUBE','CULT','CURE','CURL','CURB','CUTE','CYAN','DARE','DARK','DASH','DATA','DAWN','DAYS','DEAD','DEAF','DEAL','DEAN','DEAR','DECK','DEEP','DEER','DELL','DENS','DESK','DIAL','DICE','DIET','DIME','DINE','DIRT','DISH','DIVE','DOCK','DOLL','DOOR','DOSE','DOWN','DRAG','DRAW','DROP','DRUM','DUAL','DUCK','DUEL','DUKE','DUST','DUTY','EACH','EARN','EASE','EAST','EASY','ECHO','EDGE','EDIT','ELSE','EMIT','EPIC','EVEN','EVER','EVIL','EXIT','FACE','FACT','FADE','FAIL','FAIR','FAKE','FALL','FAME','FARM','FAST','FATE','FEAR','FEED','FEEL','FEET','FELL','FELT','FERN','FEST','FIER','FILE','FILL','FILM','FIND','FINE','FIRE','FIRM','FISH','FIST','FIVE','FLAG','FLAT','FLEA','FLEW','FLOW','FLUX','FOAM','FOLD','FOLK','FOOD','FOOL','FOOT','FORK','FORM','FORT','FOUR','FREE','FROG','FROM','FUEL','FULL','FUND','FURY','GAIN','GAME','GATE','GEAR','GEEK','GEMS','GIFT','GIRL','GIVE','GLAD','GLOW','GOAL','GOAT','GOLD','GOLF','GONE','GOOD','GRAB','GRAY','GRID','GRIP','GROW','GULF','GURU','HAIL','HAIR','HALF','HALL','HALO','HAND','HANG','HARD','HARE','HARM','HARP','HATE','HAWK','HEAD','HEAL','HEAR','HEAT','HEAV','HELP','HERB','HERO','HIDE','HIGH','HIKE','HILL','HINT','HIRE','HOLD','HOLE','HOLY','HOME','HOOD','HOOK','HOPE','HORN','HOST','HOUR','HUNT','HURT','ICON','IDEA','IDLE','IRON','ITEM','JADE','JAZZ','JOIN','JOKE','JOLT','JUMP','JUNE','JURY','JUST','KEEN','KEEP','KEYS','KICK','KILL','KIND','KING','KISS','KITE','KNEE','KNOB','KNOT','KNOW','LACE','LADY','LAKE','LAMB','LAMP','LAND','LANE','LAST','LATE','LAWN','LEAF','LEAN','LEAP','LEFT','LENS','LESS','LIFE','LIFT','LIKE','LILY','LIME','LINE','LINK','LION','LIST','LIVE','LOAD','LOAF','LOAN','LOCK','LOGO','LONE','LONG','LOOK','LOOP','LORD','LOSS','LOST','LOVE','LUCK','LUNA','LUSH','LYNX','MADE','MAIL','MAIN','MAKE','MALE','MALL','MALT','MANY','MARK','MASK','MASS','MATE','MATH','MEAL','MEAN','MEAT','MEET','MENU','MESS','MICE','MILD','MILK','MIND','MINE','MINI','MINT','MISS','MIST','MODE','MOON','MORE','MOST','MOVE','MUCH','MULE','MUSE','MYTH','NAIL','NAME','NAVY','NEAR','NEAT','NEON','NEST','NEWS','NEXT','NICE','NICK','NINE','NODE','NOON','NOSE','NOTE','NOVA',
    'ABIDE','ABODE','ABOVE','ABUSE','ACTOR','ACUTE','ADAPT','ADMIT','ADOBE','ADORE','ADULT','AFTER','AGENT','AGILE','AGLOW','AGREE','AHEAD','ALBUM','ALERT','ALIEN','ALIVE','ALLEY','ALLOW','ALONE','ALONG','ALTER','AMBER','ANGEL','ANGER','ANGLE','APPLE','APPLY','APRIL','ARENA','ARGUE','ARISE','ARROW','ASHEN','ASIDE','ASSET','ATLAS','ATOLL','AUDIO','AVOID','AWAKE','AWARD','AWARE','BACON','BADGE','BAGEL','BAKER','BALER','BALMY','BANJO','BANAL','BANER','BANJO','BANANA','BASIC','BASIN','BATCH','BATON','BEACH','BEADS','BEAST','BEGIN','BEING','BELLY','BELOW','BENCH','BERRY','BIRTH','BLACK','BLADE','BLAME','BLAST','BLAZE','BLEND','BLESS','BLIMP','BLIND','BLINK','BLISS','BLOCK','BLOOD','BLOOM','BLOWN','BLUFF','BLUNT','BOARD','BOOST','BOOTH','BORED','BORNE','BOUND','BOWEL','BOXER','BRAIN','BRAKE','BRAND','BRAVE','BREAD','BREAK','BREED','BREEZE','BRICK','BRIDE','BRIEF','BRING','BRISK','BROAD','BROKE','BROWN','BRUSH','BUILD','BULKY','BUNNY','BURST','BUYER','CABLE','CABIN','CACHE','CADET','CAMEL','CANDY','CANOE','CANON','CARRY','CARVE','CATCH','CAUSE','CEDAR','CHAIN','CHAIR','CHALK','CHAMP','CHARM','CHASE','CHEAP','CHECK','CHEER','CHESS','CHEST','CHIEF','CHILD','CHILI','CHILL','CHINA','CHOIR','CHOKE','CHORD','CHUNK','CIDER','CIGAR','CINCH','CIVIL','CLAIM','CLASH','CLASS','CLEAN','CLEAR','CLERK','CLICK','CLIFF','CLIMB','CLOCK','CLONE','CLOSE','CLOUD','CLOTH','COACH','COAST','COBRA','COCOA','COLON','COLOR','COMET','COMIC','CORAL','COUCH','COUNT','COURT','COVER','COYOTE','CRACK','CRAFT','CRANE','CRASH','CRAZY','CREAM','CREEK','CREST','CRIME','CRISP','CROWD','CROWN','CRUDE','CRUSH','CRYST','CYCLE','DAILY','DAIRY','DANCE','DANDY','DEALT','DEATH','DEBUG','DECAY','DECOR','DELAY','DELTA','DEMON','DENSE','DEPTH','DEVIL','DIARY','DICEY','DINER','DINER','DIRTY','DODGE','DOING','DONOR','DOUBT','DOZEN','DRAFT','DRAIN','DRAMA','DREAM','DRESS','DRIFT','DRILL','DRINK','DRIVE','DROPS','DRUID','DRUNK','EAGER','EAGLE','EARTH','EIGHT','ELBOW','ELDER','ELECT','ELITE','EMPTY','ENEMY','ENJOY','ENTER','ENTRY','EPOCH','EQUAL','ERROR','ESSAY','EVENT','EVERY','EXACT','EXILE','EXIST','EXTRA','FAITH','FALSE','FANCY','FAVOR','FEAST','FENCE','FEVER','FIBER','FIELD','FIEND','FIFTH','FIGHT','FINAL','FINCH','FINER','FIRST','FLAME','FLASH','FLEET','FLESH','FLICK','FLINT','FLOAT','FLOOD','FLOOR','FLOUR','FLOWN','FLUID','FOCUS','FORCE','FORGE','FORTH','FORTY','FOUND','FRAME','FRESH','FRONT','FROST','FRUIT','FULLY','FUNNY','FUSION','GIANT','GHOST','GIVEN','GLADE','GLASS','GLEAM','GLOBE','GLORY','GLOVE','GLYPH','GNOME','GOING','GRACE','GRADE','GRAIN','GRAND','GRANT','GRAPE','GRAPH','GRASS','GRAVE','GREAT','GREEN','GREET','GRIEF','GRILL','GRIND','GROVE','GUARD','GUEST','GUIDE','GUILD','HAPPY','HASTE','HAVEN','HEART','HEAVY','HELLO','HONEY','HONOR','HORSE','HOUSE','HUMAN','HUMOR','HURRY','HYDRA','IDEAL','IMAGE','INDEX','INNER','INPUT','IRONY','IVORY','JELLY','JEWEL','JOINT','JOKER','JUDGE','JUICE','KNIFE','KNOCK','KNOWN','LABEL','LASER','LATER','LAUGH','LAYER','LEARN','LEMON','LEVEL','LIGHT','LIMIT','LIVER','LOCAL','LOGIC','LONER','LOOSE','LUCKY','LUNAR','MAGIC','MAJOR','MAKER','MANGO','MAPLE','MARCH','MATCH','MAYBE','MEDAL','MERCY','METAL','MIGHT','MINOR','MODEL','MONEY','MONTH','MORAL','MOTOR','MOUSE','MOUTH','MOVIE','MUSIC','MYTHS','NAKED','NARROW','NATIVE','NAVAL','NEVER','NEXUS','NIGHT','NINJA','NOBLE','NOISE','NORTH','NOVEL','OASIS','OCEAN','OLIVE','OMEGA','ONION','OPERA','ORBIT','ORDER','ORGAN','ORIGIN','OTHER','OUTER','OWNER','OXIDE','PANEL','PANDA','PAPER','PARTY','PATCH','PEACE','PEACH','PEARL','PHASE','PHONE','PHOTO','PIANO','PIECE','PILOT','PIXEL','PIZZA','PLACE','PLAIN','PLANE','PLANT','PLATE','POINT','POKER','POWER','PRESS','PRICE','PRIME','PRINT','PRISM','PRIZE','PROUD','PROXY','PULSE','PUPPY','QUEEN','QUEST','QUICK','QUIET','QUITE','RADIO','RAINY','RALLY','RANGE','RAPID','RAVEN','RAZOR','REACH','READY','REALM','REBEL','RELIC','REMIX','RENEW','RHINO','RIDER','RIFLE','RIGHT','RIVAL','RIVER','ROBIN','ROBOT','ROCKY','ROGUE','ROMAN','ROYAL','RUGBY','RULER','RURAL','RUSTY','SABER','SAINT','SALAD','SALTY','SCALE','SCARF','SCENE','SCOPE','SCOUT','SCREW','SEVEN','SHADE','SHAKE','SHAPE','SHARK','SHARP','SHEEP','SHELL','SHIFT','SHINE','SHOCK','SHOOT','SHORT','SHOUT','SHRUB','SIGHT','SILKY','SILVER','SINCE','SKILL','SKULL','SLASH','SLATE','SLEEP','SLICE','SLOPE','SMART','SMILE','SMOKE','SNAKE','SOLAR','SOLID','SONIC','SOUND','SOUTH','SPACE','SPARK','SPEAR','SPEED','SPELL','SPICE','SPINE','SPIRIT','SPORE','SPORT','SPRAY','SQUAD','STACK','STAGE','STAIN','STAIR','STAKE','STAND','STARE','START','STATE','STEAM','STEEL','STONE','STORM','STORY','STRAW','STRIP','STYLE','SUGAR','SUNNY','SUPER','SWORD','TABLE','TAKEN','TALON','TASTE','TEACH','THANK','THEME','THIEF','THORN','THROW','TIGER','TITLE','TODAY','TOKEN','TOOTH','TORCH','TOTAL','TOUCH','TOUGH','TOWER','TOXIC','TRACE','TRACK','TRADE','TRAIN','TRIAL','TRIBE','TRICK','TRUCK','TRULY','TRUNK','TRUST','TRUTH','TULIP','TWICE','ULTRA','UNDER','UNION','UNITY','UPPER','URBAN','USAGE','VALUE','VAULT','VENOM','VENUS','VERGE','VIBES','VIDEO','VIGOR','VILLA','VINYL','VIRAL','VIRUS','VISOR','VITAL','VIVID','VOICE','VOLTS','VOTER','WAGON','WATER','WAVES','WHALE','WHEAT','WHEEL','WHERE','WHILE','WHITE','WHOLE','WIDOW','WILLY','WINDS','WINGS','WITCH','WORLD','WORRY','WORTH','WOUND','WRATH','WRITE','YACHT','YEARN','YIELD','YOUNG','YOUTH','ZEBRA','ZENITH','ZESTY',
    'ABROAD','ABSENT','ABSORB','ACCEPT','ACCESS','ACCUSE','ACROSS','ACTION','ACTIVE','ACTUAL','ADMIRE','ADVICE','ADVISE','AFFORD','AFRAID','AGENCY','AGENDA','AIRCRA','ALMOST','ALWAYS','AMOUNT','ANCHOR','ANCIEN','ANIMAL','ANNUAL','ANSWER','ANYONE','APPEAL','APPEAR','AROUND','ARRIVE','ARTIST','ASPECT','ASSERT','ASSIGN','ASSIST','ASSUME','ASSURE','ATTACK','ATTEND','AUGUST','AUTHOR','AUTUMN','AVENUE','BACKUP','BADGER','BAKERY','BALCON','BALLOO','BAMBOO','BANNER','BARREL','BASKET','BATTLE','BEACON','BEAUTY','BECOME','BEFORE','BEHALF','BEHAVE','BEHIND','BELIEF','BELONG','BERLIN','BETTER','BEYOND','BINARY','BISHOP','BITTER','BLANKET','BLASTER','BLAZER','BLEACH','BLONDE','BLOODY','BLOUSE','BOARDS','BORDER','BOTTLE','BOTTOM','BOUNCE','BOWLER','BOXING','BRANCH','BRAVES','BREATH','BREEZE','BRIDGE','BRIGHT','BROKEN','BRONZE','BUBBLE','BUDGET','BUFFER','BULLET','BUNDLE','BURGER','BURDEN','BUTTON','BUYING','CABINET','CACTUS','CAMERA','CANARY','CANDLE','CANNON','CANVAS','CAREER','CARPET','CARROT','CASTLE','CATTLE','CAUTION','CAVERN','CELEST','CENTER','CEREAL','CHANCE','CHANGE','CHARGE','CHERRY','CHOICE','CHOOSE','CHROME','CHURCH','CIRCLE','CLIENT','CLIMAX','CLOSET','CLOVER','COFFEE','COLUMN','COMBAT','COMEDY','COMING','COMMIT','COMMON','COOKIE','COPPER','CORNER','COTTON','COUNTY','COUPLE','COURSE','COVERT','CREATE','CREDIT','CREEPY','CRIMSON','CRISIS','CRYSTAL','CUSTOM','DAMAGE','DANGER','DARING','DECADE','DECENT','DECIDE','DEFEND','DEGREE','DEMAND','DEPART','DEPEND','DEPOSIT','DESERT','DESIGN','DESIRE','DETAIL','DEVICE','DEVOTE','DIAMOND','DINNER','DIRECT','DOCTOR','DOLLAR','DOMAIN','DONATE','DOUBLE','DRAGON','DRAWER','DREAMY','DRIVER','DURING','EAGLES','EARTHY','EASILY','EFFECT','EFFORT','EIGHTY','ELBOWS','ELDERS','ELECT','ELIXIR','EMBLEM','EMERALD','EMPIRE','EMPLOY','ENABLE','ENDURE','ENERGY','ENGINE','ENOUGH','ENSURE','ENTIRE','EQUITY','ESCAPE','ESTATE','ETHICS','EUROPA','EXCEPT','EXCUSE','EXHALE','EXPAND','EXPERT','EXPORT','EXTEND','EXTENT',
    'FABRIC,FACING,FACTOR,FAILED,FAIRLY,FALCON,FALLEN,FAMILY,FAMOUS,FANTASY,FARMER,FASHION,FATHER,FELLOW,FEMALE,FIERCE,FILTER,FINALE,FINGER,FINISH,FIRELY,FIRMER,FISCAL,FISHER,FLAMER,FLAMING,FLAVOR,FLOWER,FLYING,FOCUSED,FOGGER,FOLLOW,FORCED,FOREST,FORGET,FORMAL,FORMAT,FORTUN,FORWARD,FOSSIL,FOUNDRY,FRAGILE,FRAMER,FREEDOM,FREEZE,FRENZY,FRIEND,FRIGHT,FROZEN,FUTURE,GALAXY,GAMBLE,GARDEN,GARLIC,GATHER,GEARUP,GENERAL,GENIUS,GENTLE,GERMAN,GHOSTS,GIGGLE,GINGER,GLACIER,GLANCE,GLIDER,GLOBAL,GOLDEN,GOTTEN,GRANDE,GRANIT,GRAPPLE,GRASSY,GRAVEL,GREEDY,GREETS,GROUND,GROWTH,GUARDS,GUITAR,HABBIT,HACKER,HAMMER,HANDLE,HANGER,HARBOR,HARDEN,HARMON,HARVEST,HAZARD,HEADED,HEALER,HEALTH,HEARTS,HEAVEN,HEIGHT,HELPER,HIDDEN,HOLDER,HONEST,HUNGER,HUNTER,HYBRID,ICICLE,IGNORE,IMPACT,IMPORT,INCOME,INDEED,INDIGO,INFECT,INFORM,INJURY,INSECT,INSIDE,INSPIRE,INTAKE,INVITE,ISLAND,ITSELF,JACKET,JAGUAR,JASMIN,JERSEY,JETWAY,JINGLE,JOURNY,JUDGED,JUNGLE,JUNIOR,KEEPER,KERNEL,KETTLE,KEYPAD,KIDNAP,KITTEN,KNIGHT,LADDER,LAGOON,LAMBDA,LANTERN,LAPTOP,LARGER,LASERS,LASTLY,LATTER,LAUNCH,LAVENDER,LAWYER,LEADER,LEAGUE,LEAFER,LEGACY,LEGEND,LENDER,LENGTH,LESSON,LETTER,LEVELS,LIBERT,LIBRARY,LIGHTS,LIKELY,LILIES,LIMITER,LINEAR,LIQUID,LISTEN,LITTLE,LOADER,LOCKER,LONELY,LOOKER,LOVELY,LUMBER,LUXURY,MAGNET,MAIDEN,MAJEST,MAKING,MANNER,MANUAL,MAPLES,MARGIN,MARINE,MARKER,MARVEL,MASKED,MASTER,MATRIX,MATTER,MEADOW,MEDIUM,MEMBER,MEMORY,MERCURY,MERGER,METHOD,MIDDLE,MIGHTY,MILLER,MINERAL,MINING,MIRROR,MISSION,MOBILE,MODERN,MODULE,MOMENT,MONKEY,MONTHS,MORNING,MOTHER,MOTION,MOUNTS,MOVING,MUFFIN,MURDER,MUSCLE,MUSEUM,MUTANT,MYSELF,MYSTIC',
    'NATION,NATIVE,NATURE,NEBULA,NEEDLE,NEPHEW,NETHER,NEURAL,NEUTON,NEVERY,NEXUSX,NICKEL,NIGHTY,NIMBLE,NINETY,NOBODY,NOBLER,NORMAL,NOTION,NUGGET,NUMBER,NURSER,OBJECT,OBLIGE,OBSCUR,OBTAIN,OCEANS,OFFICE,OFFSET,OMELET,ONLINE,OPENLY,OPPOSE,OPTION,ORACLE,ORANGE,ORBITS,ORCHID,ORDAIN,ORIGIN,ORNATE,OTHERS,OUTFIT,OUTLAW,OUTLET,OUTPUT,OUTRUN,OUTSID,OXFORD,PACKET,PADDLE,PALACE,PALMER,PANELS,PANTER,PARADE,PARROT,PARTLY,PASSER,PASSION,PATROL,PATTER,PAYDAY,PEANUT,PEBBLE,PENCIL,PEOPLE,PEPPER,PERFEC,PERMIT,PERSON,PETALS,PHOENX,PHOTON,PICKAX,PIECES,PILLOW,PILOTS,PIRATE,PLANET,PLAYER,PLEASE,PLENTY,PLUMER,POCKET,POETRY,POISON,POLICE,POLISH,PORTRA,POSTER,POTION,POWDER,PRAISE,PRAYER,PRETTY,PRIEST,PRINCE,PRISON,PROFIT,PROMPT,PROTON,PUBLIC,PUDDLE,PUPPET,PURPLE,PURSUE,PYTHON,QUARTZ,QUEENS,QUICKY,QUIVER,RABBIT,RACING,RADIAN,RADISH,RADIUS,RAIDER,RAILER,RAINER,RANDOM,RANGER,RAPTOR,RATHER,RAVENS,READER,REALMS,REASON,REBELS,REBOOT,RECALL,RECIPE,RECORD,REDEEM,REFLEX,REFORM,REFUGE,REGION,REJECT,RELAXX,RELICS,REMOTE,RENDER,REPAIR,REPEAT,REPORT,RESCUE,RESIST,RESULT,RETURN,REWARD,RHYTHM,RIBBON,RICHES,RIDDLE,RIDERS,RIFLES,RIPPLE,RITUAL,ROAMER,ROBBER,ROBOTS,ROCKET,ROGUES,ROLLER,ROMANCE,ROOKIE,ROOTED,ROSTER,ROTATE,ROUTER,RUBBER,RUBIES,RUNNER,RUNWAY,RUSTIC',
    'SADDLE,SAFARI,SAILOR,SALMON,SALUTE,SAMPLE,SATURN,SAVAGE,SAVIOR,SCARAB,SCENIC,SCHOOL,SCIENT,SCORCH,SCOUTS,SCRAPE,SCREEN,SCRIPT,SCROLL,SCULPT,SEARCH,SEASON,SECRET,SECURE,SELECT,SENIOR,SENSOR,SERENE,SERVER,SHADOW,SHAMAN,SHIELD,SHIVER,SHRINE,SIGNAL,SILENT,SILVER,SIMPLE,SINGLE,SISTER,SKATER,SKETCH,SKYWAY,SLAYER,SLICER,SMOOTH,SNIPER,SOLARIS,SOLDIER,SOLVED,SPACER,SPARKS,SPEECH,SPEEDY,SPELLS,SPHERE,SPIDER,SPIRIT,SPLASH,SPOKEN,SPRING,SPRITE,SQUARE,STABLE,STANCE,STARRY,STATUE,STEADY,STEALTH,STELLAR,STICKY,STINGER,STREAM,STREET,STRIKE,STRING,STRONG,STUDIO,SUMMER,SUMMIT,SUNSET,SUPPLY,SUPPORT,SURELY,SURFER,SURGER,SURVEY,SWITCH,SYMBOL,SYSTEM,TABLET,TACKLE,TACTIC,TAILOR,TALENT,TARGET,TEMPLE,TENDER,TENNIS,TERROR,THEORY,THRONE,TICKET,TIMBER,TISSUE,TITANI,TOMATO,TORNAD,TOWERS,TRACER,TRADER,TRAILS,TRAVEL,TREASURE,TREATY,TRIBAL,TRICKS,TRINITY,TROPHY,TROPIC,TRUSTY,TUNNEL,TURBOO,TURTLE,TWILIGHT,TYPING,UNIQUE,UNITED,UNREAL,UPDATE,UPLIFT,UPWARD,URGENT,VALLEY,VALORR,VANISH,VECTOR,VELVET,VENDOR,VERMIL,VICTOR,VISION,VISUAL,VIVACE,VOYAGE,WALNUT,WANDER,WARDEN,WARMTH,WARRIOR,WATERF,WEALTH,WEAPON,WEEKLY,WELCOME,WESTER,WHISKY,WINDOW,WINNER,WINTER,WISDOM,WIZARD,WONDER,WOODEN,WORKER,WORTHY,WRITER,YELLOW,YONDER,ZEPHYR,ZODIAC',
    'ADMIXT,ALMOND,ALPINE,ANCHOR,APRONS,ARCHER,ARMORY,ARROWS,ARTFUL,ASHORE,ASTRAL,AUBURN,AURORA,BADGER,BALLET,BAMBOO,BANISH,BARBER,BARGER,BARLEY,BEACHS,BELONG,BERLIN,BETRAY,BEYOND,BINDER,BLOSSOM,BOATER,BONNET,BOREAL,BORROW,BOSTON,BOULDER,BRANCH,BRIAR,BRONCO,BROOMS,BRUTAL,BUBBLE,BUFFER,BUTTER,CACTUS,CALCUL,CAMPER,CANARY,CANDLE,CANVAS,CAPTOR,CAPSUL,CAPTAIN,CARBON,CARPET,CARTON,CASCADE,CASHEW,CASTER,CAUCUS,CAVITY,CELERY,CENTER,CEREAL,CHAINS,CHANCE,CHANGE,CHAPEL,CHARGE,CHARMS,CHERRY,CHISEL,CHOICE,CHORUS,CIPHER,CITRUS,CLARITY,CLIMAX,CLOVER,COBALT,COCOON,COFFEE,COLLAR,COMBAT,COMETS,COMICS,COOKIE,COPPER,CORNER,CORONA,COSMOS,COTTON,COUGAR,COUPON,CRATER,CRIMSON,CRUNCH,CRYSTAL,CUSTOM,DANCER,DANGER,DARING,DASHER,DECADE,DECENT,DECIDE,DEFEAT,DEFEND,DEGREE,DELIGHT,DEMONS,DENSER,DESERT,DESIGN,DESIRE,DEVICE,DIAMOND,DINNER,DIRECT,DOCTOR,DOLPHN,DOMAIN,DONKEY,DOUBLE,DRAGON,DREAMS,DRIVER,DURIAN,EAGLES,EARTHS,ECHOES,EFFECT,EFFORT,ELIXIR,EMBLEM,EMERALD,EMPIRE,ENABLE,ENDURE,ENERGY,ENGINE,ENOUGH,ENSURE,ENTIRE,ESCAPE,ESTATE,ETHICS,EUROPE,EXCEPT,EXCUSE,EXPERT,EXPORT,EXTEND,FABRIC,FALCON,FAMILY,FAMOUS,FANTASY,FARMER,FASHION,FATHER,FELLOW,FEMALE,FIANCE,FIERCE,FILTER,FINALE,FINGER,FINISH,FIRELY,FISHER,FLAVOR,FLOWER,FOLLOW,FOREST,FORGET,FORMAT,FORWARD,FOSSIL,FOUNDRY,FRAGILE,FREEZE,FRENZY,FRIEND,FROZEN,FUTURE,GALAXY,GARDEN,GARLIC,GATHER,GENERAL,GENIUS,GENTLE,GHOSTS,GINGER,GLACIER,GLOBAL,GOLDEN,GRAVEL,GROWTH,GUARDS,GUITAR,HACKER,HAMMER,HANDLE,HARBOR,HARVEST,HAZARD,HEALER,HEALTH,HEAVEN,HEIGHT,HELPER,HIDDEN,HOLDER,HONEST,HUNGER,HUNTER,HYBRID,IGNORE,IMPACT,IMPORT,INCOME,INDIGO,INSECT,INSIDE,INSPIRE,INVITE,ISLAND,JACKET,JAGUAR,JASMIN,JERSEY,JINGLE,JUNGLE,JUNIOR,KEEPER,KERNEL,KETTLE,KITTEN,KNIGHT,LADDER,LAGOON,LANTERN,LAPTOP,LAUNCH,LAWYER,LEADER,LEAGUE,LEGACY,LEGEND,LENDER,LENGTH,LESSON,LETTER,LIBRARY,LIGHTS,LINEAR,LIQUID,LISTEN,LITTLE,LOCKER,LONELY,LOVELY,LUXURY,MAGNET,MAIDEN,MAKING,MANNER,MANUAL,MARINE,MARKER,MARVEL,MASKED,MASTER,MATRIX,MEADOW,MEDIUM,MEMBER,MEMORY,MERCURY,METHOD,MIDDLE,MIGHTY,MINERAL,MIRROR,MISSION,MOBILE,MODERN,MODULE,MOMENT,MONKEY,MORNING,MOTHER,MOTION,MUFFIN,MUSCLE,MUSEUM,MUTANT,MYSTIC',
    'ABILITY,ABSENCE,ACADEMY,ACCOUNT,ACHIEVE,ACQUIRE,ADDRESS,ADVANCE,ADVISER,AIRPORT,ALCHEMY,ALLEGRO,ALLIANCE,AMBIENT,ANCIENT,ANCHORS,ANOTHER,APPEARS,ARCHERS,ARCTICS,ARMOURY,ARRIVAL,ARTWORK,ASCENDS,ASHLAND,ASPHALT,ASSASSIN,ASTRONA,ATHLETE,ATLASER,AURORAS,AVENGER,BALANCE,BALLOON,BAMBOOS,BARRIER,BATTERY,BEACONS,BEARING,BEAUTYS,BELIEVE,BENEFIT,BESPOKE,BETRAYAL,BEYONDS,BILLION,BLOSSOM,BLUEBER,BOULDER,BRAVERY,BREEZES,BRIGHTS,BROTHER,BUFFALO,BUILDER,BULLETS,BURDENS,CALIBER,CAMPING,CAPTAIN,CAPTURE,CARDINAL,CARIBOU,CARRIER,CASCADE,CASPIAN,CELESTE,CENTAUR,CENTURY,CERAMIC,CHAMBER,CHAMPION,CHARIOT,CHARMER,CHECKER,CHEETAH,CHERRYS,CHIMERA,CHRONIC,CIRCUIT,CITIZEN,CLARITY,CLEANER,CLOUDBY,CLOVERS,COMMAND,COMPASS,CONNECT,CONQUER,CONTROL,COOKIES,CORSAIR,COSMOSX,COURAGE,CRIMSON,CRYSTAL,CUPCAKE,CURIOUS,CUSTOMS,CYCLONE,DANCING,DARKNESS,DAZZLER,DEFENCE,DELIGHT,DENSITY,DESTINY,DIAMOND,DISCOVER,DISPLAY,DOLPHIN,DOMINION,DRAGONS,DREAMER,DYNAMIC,ECLIPSE,ELECTRO,ELEGANT,EMERALD,EMOTION,EMPEROR,EMPIREX,ENDLESS,ENIGMAS,ENJOYER,EPISODE,EQUATOR,ESSENCE,ETERNAL,EVEREST,EVOLVED,EXCALIB,EXPLORER,FACTORY,FALCONS,FANTASY,FARMING,FASHION,FEATHER,FERRARI,FIREFLY,FIREFOX,FIREMAN,FISHING,FLAWLESS,FLEXION,FLOWERS,FOREVER,FORTUNE,FREEDOM,FRIENDS,FRONTIER,FUSIONS,GALAXYX,GAMBLER,GARDENS,GATEWAY,GENERAL,GENESIS,GLACIER,GLORIFY,GOLDENS,GUARDIAN,HAMMERS,HANGMAN,HARMONY,HARVEST,HEALING,HEAVENS,HEROICS,HORIZON,HUNTERS,ICEBERG,ILLUSION,IMAGINE,IMMORTAL,IMPACTS,IMPERIA,IMPROVE,INFERNO,INFINITE,INSIGHT,INSPIRE,ISLANDS,JOURNEY,JUNGLES,JUSTICE,KINGDOM,KNIGHTS,LANTERN,LEGENDS,LIBERTY,LIONESS,MACHINE,MAJESTY,MARBLES,MARSHAL,MAVERICK,MEADOWS,MERCURY,MESSAGE,MILLION,MIRACLE,MISSION,MONARCH,MONSTER,MYSTERY,MYSTICS,NATURAL,NEBULAS,NEMESIS,NETWORK,NEUTRON,NIRVANA,NOMADIC,NOTABLE,NOVELTY,OASISES,OBSIDIAN,OCEANIC,OFFLINE,OLYMPUS,ORACLES,ORCHARD,OUTCAST,OVERLORD,PALADIN,PANTHER,PARAGON,PASSION,PATRIOT,PEGASUS,PHANTOM,PHOENIX,PILGRIM,PIONEER,PLANETS,PLATINUM,POWERUP,PRELUDE,PRESTIGE,PRINCES,PRODIGY,PROMISE,PROTECT,PYRAMID,QUANTUM,QUESTER,RADIANT,RAINBOW,RANGERS,RAPTURE,REBIRTH,REACTOR,REALITY,REDEMPT,REFLECT,REGALIA,RELIANT,RESONANCE,RESPAWN,REVENGE,RHYTHMS,RIVIERA,ROCKETS,ROYALTY,RUNNERS,SAFEGUARD,SAPPHIRE,SCARLET,SCHOLAR,SCORPION,SEASIDE,SENTINEL,SHADOWS,SHAMANS,SHERIFF,SHOOTER,SILENCE,SILVERS,SKYLINE,SOLDIER,SOLSTICE,SPARTAN,SPECTRA,SPEEDER,SPHINX,SPIRITS,STARLIT,STARMAN,STARWAY,STELLAR,STORMER,STRIKER,SUCCESS,SUMMONS,SUNRISE,SUNSHINE,SURGEON,SURVIVE,SWORDMAN,SYNERGY,TALISMAN,TEMPEST,THUNDER,TITANIUM,TORNADO,TRAVELL,TRIDENT,TRINITY,TROOPER,TROUBLE,TWILIGHT,UNICORN,UNIFIED,UNLIMIT,UPGRADE,VALHALLA,VALIANT,VANQUISH,VELVETY,VICTORY,VIGILANT,VILLAIN,VIOLETS,VIRTUAL,VISIONS,VOLCANO,VOYAGER,WANDERS,WARLOCK,WARRIOR,WELCOME,WILDFIRE,WILLOWS,WINDOWS,WINNERS,WISDOMS,WIZARDS,WONDERS,WYVERNS,ZEPHYRS,ZODIACS',
    'ABSOLUTE,ACADEMIC,ACCURACY,ACCURATE,ADVENTURE,AIRBORNE,ALCHEMIST,ALLIANCE,ALMIGHTY,ALPHABET,AMBITION,ANCIENTS,ANIMATOR,ANYWHERE,APOCALYPSE,AQUAMARINE,ARBITRAGE,ARCADEON,ARCHAIC,ARCHMAGE,ARMAMENT,ARTIFACT,ASCENSION,ASSASSIN,ASTEROID,ATHLETIC,ATLANTIS,AURORIAN,AVALANCHE,AVENGERS,AWAKENED,BACKFIRE,BACKPACK,BALANCED,BALLISTA,BANISHED,BARBARIAN,BARRICADE,BATTLEAX,BATTLECR,BEARINGS,BEAUTIFY,BECKONED,BEHOLDER,BELIEVER,BENCHMARK,BERSERKR,BLACKOUT,BLACKICE,BLACKSUN,BLIZZARD,BLOODRED,BLOSSOMS,BLUEFIRE,BLUEWOLF,BODYGUARD,BOOKMARK,BOUNDARY,BRANDNEW,BRAVESTR,BREAKOUT,BRIGHTER,BROADWAY,BROTHERS,BUILDING,BULLETPR,BURNINGS,BUSINESS,CALENDAR,CAMPAIGN,CAPSTONE,CAPTAINS,CARDINAL,CARNIVAL,CASCADES,CASTAWAY,CATALYST,CAVALIER,CELEBRATE,CENTAURI,CENTURION,CHALLENG,CHAMPION,CHARISMA,CHECKMATE,CHEMICAL,CHEROKEE,CHIMERAS,CHOCOLATE,CHRONICLE,CIRCUITS,CITADELX,CITIZENS,CIVILIAN,CLASSICS,CLEANING,CLOCKWISE,CLOUDNINE,COLLAPSE,COLLECTOR,COLOSSAL,COMMANDO,COMPANION,COMPLETE,COMPOSER,COMPUTER,CONQUEST,CONSOLEX,CONSTANT,CONSUMER,CONTINUE,CONTRACT,CONVERTX,CORSAIRS,COSMOSKY,COURAGES,COVENANT,CREATION,CREATURE,CRIMSONX,CROSSING,CRUSADER,CRYSTALS,CUPCAKES,CYBERNET,DARKNESS,DARKLORD,DAYBREAK,DEADSHOT,DECEMBER,DECISION,DEEPBLUE,DEFENDER,DELICATE,DELIGHTS,DELIVERY,DENSITYX,DESIGNER,DESTINYX,DESTROYA,DIAMONDS,DIRECTOR,DISCOVER,DISTRICT,DIVINITY,DOLPHINS,DOMINATE,DOWNFALL,DRAGONIC,DREAMERS,DRIFTERS,DUNGEONS,DYNAMICS,EARTHBORN,ECLIPSES,EDGEWISE,ELEMENTS,ELEVATOR,EMBRACED,EMERALDS,EMPERORS,EMPIREON,ENCHANT,ENDURANCE,ENERGIZE,ENGINEER,ENLIGHT,ENTRANCE,EPICNESS,EQUINOX,EVERLAST,EVERMORE,EXCALIBR,EXPLORER,FALCONER,FANTASIA,FIREBIRD,FIRESTAR,FIRESTORM,FIREWALL,FORGOTTEN,FORTRESS,FREEFALL,FREEDOMS,FRONTIER,FROSTBIT,FROZENSK,GALAXIES,GATEKEEP,GENERALS,GENIUSES,GLADIATOR,GLORIOUS,GOLDMINE,GUARDIAN,HARMONIC,HARVESTS,HEADSHOT,HEARTFUL,HEAVENLY,HIGHLAND,HOLYFIRE,HORIZONS,HUNTERSX,HURRICAN,ICEBERGS,ICEBLADE,IMMORTAL,IMPERIAL,INFERNAL,INFERNOS,INFINITE,INFINITY,INSIGHTS,INSPIRED,INVISIBLE,IRONCLAD,ISOLATED,JOURNEYS,JUDGMENT,JUNCTION,KEYSTONE,KNIGHTLY,LABYRINTH,LANDMARK,LASTHOPE,LAUNCHER,LEGENDRY,LIBERTYX,LIFELINE,LIGHTING,LIONHEART,LONGLIFE,LORDSHIP,MACHINEX,MAELSTRM,MAGNIFIC,MAJESTIC,MARSHALL,MAVERICK,MECHANIC,MEMORIES,MERCENRY,MIDNIGHT,MILESTONE,MIRACLES,MONARCHY,MOONLIGHT,MOUNTAIN,MYSTICAL,NAVIGATE,NEBULAE,NEMESISS,NIGHTFALL,NIGHTOWL,NIGHTSKY,NIRVANAX,NOBILITY,NORTHERN,OBLIVION,OCEANIDE,OFFSHORE,OLYMPIAN,OMEGAFOR,ONCOMING,ORBITALS,ORCHIDEE,OUTBREAK,OUTSIDER,OVERCOME,OVERLORD,PALADINS,PANORAMA,PARADISE,PATHFIND,PATRIOTS,PEGASUSX,PERFECTO,PHANTOMS,PHOENIXS,PIERCING,PIONEERS,PLATINUM,POWERFUL,PREDATOR,PREMIERE,PRESTIGE,PRIMROSE,PRINCELY,PRODIGYX,PROPHETS,PROSPERX,PROTECTR,PYRAMIDS,QUANTUMX,QUESTING,RADIANCE,RAINBOWS,RAPIDFIRE,RAVENOUS,REACTORS,REBIRTHS,REDEMPTION,REFLECTS,RELIABLE,REMEDIES,RENEGADE,RESONANT,RESPAWNS,REVENANT,REVOLVER,RIVERBANK,ROYALTYX,RUNICWAR,SAFEGUARD,SAPPHIRE,SCARLETX,SCHOLARS,SCORPION,SEASHELL,SENTINEL,SHADOWED,SHIELDER,SHOOTING,SILENCER,SILVERMO,SKYGUARD,SKYWATCH,SOLSTICE,SOULMATE,SPARTANS,SPECTRAL,SPELLBOOK,STARFALL,STARFIRE,STARLIGHT,STEELMAN,STORMBRN,STORMRID,STRATEGY,STRENGTH,STRIKERS,SUNFLOWER,SUNRISES,SUPERNOVA,SURVIVAL,SWORDSMAN,SYMPHONY,TALISMAN,TEMPESTX,TERRAFORM,THUNDERX,TITANIUM,TORNADOS,TRACKING,TRAVELER,TREASURE,TRIDENTX,TRIUMPHS,TROOPERS,TWILIGHT,ULTIMATE,UMBRELLA,UNICORNS,UNIVERSE,UPLIFTED,VALHALLA,VALKYRIE,VANGUARD,VANQUISH,VICTORIA,VICTORIA,VICTORYX,VIGILANT,VINTAGEX,VIRTUOUS,VOLCANIC,VOYAGERS,WARLORDS,WARRIORS,WATERFALL,WESTWARD,WHIRLWIND,WILDFIRE,WINDSTORM,WINGSPAN,WINTERS,WONDERER,WOODLAND,WORKSHOP,WRATHFUL,YOUNGEST,ZEPHYRUS,ZODIACAL',
    'CHAD','CUBA','FIJI','IRAN','IRAQ','LAOS','MALI','OMAN','PERU','TOGO','NIUE','BENIN','CHILE','CHINA','EGYPT','GABON','GHANA','HAITI','INDIA','ITALY','JAPAN','KENYA','LIBYA','MALTA','NAURU','NEPAL','NIGER','PALAU','QATAR','SAMOA','SPAIN','SUDAN','SYRIA','TONGA','YEMEN','ANGOLA','BELIZE','BHUTAN','BRAZIL','BRUNEI','CANADA','CYPRUS','FRANCE','GAMBIA','GREECE','GUINEA','ICELAND','ISRAEL','JORDAN','KOSOVO','KUWAIT','LATVIA','LEBANON','MALAWI','MEXICO','MONACO','MOROCCO','NORWAY','POLAND','RWANDA','SERBIA','SWEDEN','TAIWAN','TUNISIA','TURKEY','UGANDA','UKRAINE','ZAMBIA','ALBANIA','ARMENIA','AUSTRIA','BAHRAIN','BELARUS','BELGIUM','BOTSWANA','BULGARIA','CAMBODIA','CAMEROON','COLOMBIA','CROATIA','DENMARK','DJIBOUTI','DOMINICA','ECUADOR','ERITREA','ESTONIA','ETHIOPIA','FINLAND','GEORGIA','GRENADA','HUNGARY','INDONESIA','IRELAND','JAMAICA','LESOTHO','LIBERIA','MALAYSIA','MAURITIUS','MOLDOVA','MONGOLIA','MYANMAR','NAMIBIA','NIGERIA','PAKISTAN','PARAGUAY','PORTUGAL','ROMANIA','SENEGAL','SINGAPORE','SLOVAKIA','SLOVENIA','SOMALIA','SURINAME','SWAZILAND','TANZANIA','THAILAND','TRINIDAD','URUGUAY','VENEZUELA','ZIMBABWE','ARGENTINA','AUSTRALIA','AZERBAIJAN','BANGLADESH','BARBADOS','BELARUS','BULGARIA','COSTARICA','DOMINICA','ESWATINI','GUATEMALA','HONDURAS','KAZAKHSTAN','KYRGYZSTAN','LUXEMBOURG','MACEDONIA','MADAGASCAR','MAURITANIA','MICRONESIA','MONTENEGRO','MOZAMBIQUE','NICARAGUA','PHILIPPINES','SANMARINO','SIERRALEONE','SOUTHKOREA','SOUTHSUDAN','SRILANKA','SWITZERLAND','TAJIKISTAN','TIMORLESTE','TURKMENISTAN','UKRAINE','UZBEKISTAN',
    'AJAX','ASAN','BARI','BERN','DOHA','HILO','KOBE','LEON','LIMA','LODZ','LYON','MESA','MIKO','OSLO','PISA','RIGA','ROME','SALE','SANA','SUVA','YORK','ADANA','AGRA','AKRON','ALMAT','AMMAN','ATHEN','BAKU','BASRA','BATAM','BELEM','BERNE','BILBA','BOGOR','BRAGA','BRNO','BRUGE','BUSAN','CAIRO','CANNES','CHIBA','DELHI','DUBAI','DURBAN','EDIRN','ESPOO','FARGO','GENOA','GHENT','GOYANG','HOBAR','IBIZA','INCHEON','IZMIR','JAIPUR','JEDDA','KANAZ','KARLS','KATOW','KRAKO','KYOTO','LEEDS','LEIPZ','LILLE','LIVER','MACAO','MALMO','MIAMI','MILAN','MINSK','NAGOY','NANJG','NICEA','OSAKA','PARIS','PERTH','PUSAN','QINGD','RABAT','RENOX','SEOUL','SEVIL','SOCHI','SOFIA','SPLIT','SURAT','SYDNY','TAIPE','TIANJ','TOKYO','TURIN','ULSAN','VENICE','VIENN','WARSA','WUHAN','XIAMEN','AARHUS','ADDLIS','ANKARA','ATHENS','AUSTIN','BANGOR','BANGUI','BARCEL','BEIJING','BELFAST','BERGEN','BERLIN','BOSTON','BRISBN','BRUSSE','BUDAPE','CALCUT','CANBER','CARDIF','CHENGD','CHICAG','DAEGU','DAEJON','DALLAS','DENVER','DETROI','DRESDN','DUBLIN','FLOREN','FUKUOK','GENEVA','GOTHEN','HAMBUR','HANOI','HAVANA','HELSIN','HOUSTN','JAKART','KARACH','KOBLEN','KOLN','KUWAIT','LAGOS','LAHORE','LISBON','LONDON','MADRID','MANILA','MELBOU','MEXICO','MINSKY','MOSCOW','MUMBAI','MUNICH','NAGOYA','NAIROB','NAPLES','NEWARK','NICEFR','OXFORD','PALERM','PHOENX','PRAGUE','QUEBEC','RIODEJ','ROTTER','SALZBG','SAPPOR','SEATTL','SHANGH','SHENZH','SINGAP','STOCKH','SYDNEY','TAIPEI','TASHKE','TBILIS','TORONT','VALENC','VANCOU','VENICE','VIENNA','WARSAW','WROCLA','ANTWERP','BANGKOK','BELFAST','BOLOGNA','BRISBANE','BRUSSELS','BUCHARE','BUDAPES','CHARLOT','CHICAGO','COLOGNE','CURITIB','FLORENCE','FRANKFU','FUKUOKA','HAMBURG','HANGZHOU','HOUSTON','ISTANBU','JAKARTA','KARACHI','KRAKOW','LASVEGA','LEICEST','LIVERPO','LOSANGE','MADISON','MANCHE','MARSEIL','MELBOUR','MONTREA','MUNSTER','NAGOYA','NASHVIL','NEWYORK','OAKLAND','PALERMO','PHILADE','PHOENIX','PORTLAN','SANJOSE','SANTIAG','SAPPORO','SHANGHA','SHENZHE','SINGAPO','STUTTGA','TAIPEI','TORONTO','VALENCIA','VANCOUV','WARSAW','WELLING','AMSTERDAM','AUCKLAND','BALTIMORE','BARCELONA','BIRMINGHAM','BRASILIA','BRATISLAVA','BUDAPEST','CAPETOWN','CINCINNATI','COPENHAGEN','EDINBURGH','FRANKFURT','GUANGZHOU','HAMBURGX','HONOLULU','HYDERABAD','ISTANBUL','LASVEGAS','LIVERPOOL','LOSANGELES','MELBOURNE','MINNEAPOLIS','MONTREAL','NASHVILLE','NEWORLEANS','PHILADELPHIA','PITTSBURGH','ROTTERDAM','SANANTONIO','SANFRANCISCO','SANTIAGO','SHANGHAI','SINGAPORE','STOCKHOLM','STRASBOURG','STUTTGART','TALLINN','TIANJIN','VANCOUVER','WASHINGTON','WELLINGTON','YOKOHAMA','ZURICH'

  ];


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage('');

    // 1. 유효성 검증
    const codeRegex = /^[A-Z0-9]{4,8}$/;
    if (!codeRegex.test(formData.referralCode)) {
      setErrorMessage('인플루언서 코드는 영문 대문자와 숫자 조합의 4~8글자여야 합니다.');
      return;
    }
    // [추가] 프리미엄 고유명사 단어 단독 사용 제한 로직
    // 입력된 코드가 금지 단어 목록에 완전히 일치하는지 확인 (예: 'LOVE'는 참, 'LOVE1'은 거짓)
    const isBlacklisted = PREMIUM_BLACKLIST.includes(formData.referralCode);
    if (isBlacklisted) {
      setErrorMessage(`'${formData.referralCode}' 사용할 수 없는 코드입니다. 다른 코드를 입력하거나 뒤에 숫자를 조합해 주세요. (예: ${formData.referralCode}1)`);
      setIsLoading(false);
      return;
    }


    if (!isAgreed) {
      setErrorMessage('개인정보 수집 및 이용에 동의해 주세요.');
      return;
    }

    // 2. Supabase 등록 프로세스 시작
    setIsLoading(true);

    try {
      // [추가] 2-1. 이름과 연락처가 동일한 기존 신청 내역이 있는지 확인
      // 반려(REJECTED)된 데이터는 재신청이 가능하도록 status가 REJECTED가 아닌 것만 조회합니다.
      const { data: existingUser, error: userCheckError } = await supabase
        .from('influencers')
        .select('status')
        .eq('name', formData.name)
        .eq('phone', formData.phone)
        .neq('status', 'REJECTED') // 'REJECTED'가 아닌 데이터가 있다면 이미 신청한 사람임
        .maybeSingle();

      if (userCheckError) throw userCheckError;

      if (existingUser) {
        if (existingUser.status === 'PENDING') {
          setErrorMessage('이미 인플루언서 리워드를 신청하여 심사 대기 중인 연락처입니다.');
        } else if (existingUser.status === 'APPROVED') {
          setErrorMessage('이미 승인된 인플루언서입니다. 포인트 조회 페이지를 이용해 주세요.');
        }
        setIsLoading(false);
        return;
      }

      // 2-2. 인플루언서 코드 중복 체크 (기존 로직 유지)
      const { data: existingCode, error: codeCheckError } = await supabase
        .from('influencers')
        .select('referral_code')
        .eq('referral_code', formData.referralCode)
        .maybeSingle();

      if (codeCheckError) throw codeCheckError;

      if (existingCode) {
        setErrorMessage('이미 사용 중이거나 신청된 인플루언서 코드입니다. 다른 코드를 입력해주세요.');
        setIsLoading(false);
        return;
      }

      // 2-3. 데이터 삽입 (기존 로직 유지)
      const { error: insertError } = await supabase
        .from('influencers')
        .insert([
          {
            name: formData.name,
            phone: formData.phone,
            sns_channel: formData.snsChannel,
            referral_code: formData.referralCode,
            status: 'PENDING'
          }
        ]);

      if (insertError) throw insertError;

      alert('인플루언서 리워드 신청이 완료되었습니다! 검토 후 승인까지 시일이 소요될 수 있습니다.');
      setFormData({ name: '', phone: '', snsChannel: '', referralCode: '' });
      setIsAgreed(false);

    } catch (error: unknown) {
      console.error('인플루언서 등록 에러:', error);
      if (error instanceof Error) {
        setErrorMessage(`신청 처리 중 오류가 발생했습니다: ${error.message}`);
      } else {
        setErrorMessage('신청 처리 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8F9FD] flex flex-col items-center justify-start px-4 py-8 text-[#333333]">
      
      <div className="flex justify-start">
        <Link href="/" >
            <Image
            src="/images/dimof-logo.png"
            alt="디모프 로고"
            width={110}
            height={36}
            priority
          />
      </Link>
      
      
      </div>

      {/* 헤더 섹션 */}
      <div className="w-full max-w-md text-left mb-6 px-1">
        <br>
      </br>
        <h1 className="text-2xl font-bold text-[#000000]">인플루언서 리워드 신청</h1>
        <p className="text-sm text-[#A78BFA] mt-1">
          인플루언서 코드를 입력한 주문의 결제금액 10%를 적립해드립니다.
        </p>
      </div>

      {/* 메인 신청 폼 카드 */}
      <form 
        onSubmit={handleSubmit}
        className="w-full max-w-md bg-white border border-[#EDE9FE] rounded-3xl p-6 shadow-sm flex flex-col gap-6"
      >
        <div className="flex justify-between items-center border-[#F5F3FF] pb-3">
          <span className="text-base font-semibold text-[#000000]">신청자 정보 입력</span>
        </div>

        {/* 이름 입력 (최대 15자) */}
        <div className="flex flex-col gap-2">
          <label className="text-sm font-semibold text-[#000000] px-1">이름</label>
          <input
            type="text"
            name="name"
            maxLength={15}
            required
            disabled={isLoading}
            value={formData.name}
            onChange={handleChange}
            placeholder="홍길동 (최대 15자)"
            className="w-full px-4 py-3 border border-[#E9E3FF] rounded-2xl focus:outline-none focus:ring-2 focus:ring-[#C084FC] focus:border-transparent transition-all placeholder:text-[#aaaaaa] disabled:bg-gray-50"
          />
        </div>

        {/* 연락처 입력 (숫자만 가능) */}
        <div className="flex flex-col gap-2">
          <label className="text-sm font-semibold text-[#000000] px-1">연락처</label>
          <input
            type="tel"
            name="phone"
            required
            disabled={isLoading}
            value={formData.phone}
            onChange={handleChange}
            placeholder="숫자만 입력해 주세요 (예: 01012345678)"
            className="w-full px-4 py-3 border border-[#E9E3FF] rounded-2xl focus:outline-none focus:ring-2 focus:ring-[#C084FC] focus:border-transparent transition-all placeholder:text-[#aaaaaa] disabled:bg-gray-50"
          />
        </div>

        {/* SNS 채널 링크 입력 */}
        <div className="flex flex-col gap-2">
          <label className="text-sm font-semibold text-[#000000] px-1">SNS 채널 주소</label> 
          <input
            name="snsChannel"
            required
            disabled={isLoading}
            value={formData.snsChannel}
            onChange={handleChange}
            placeholder="@dimof_official 또는 네이버블로그 주소"
            className="w-full px-4 py-3 border border-[#E9E3FF] rounded-2xl focus:outline-none focus:ring-2 focus:ring-[#C084FC] focus:border-transparent transition-all placeholder:text-[#aaaaaa] disabled:bg-gray-50"
          />
        </div>

        {/* 희망 인플루언서 코드 입력 (4~8자) */}
        <div className="flex flex-col gap-2">
          <div className="flex justify-between items-center px-1">
            <label className="text-sm font-semibold text-[#000000]">희망 인플루언서 코드</label>
            <span className="text-xs text-[#A78BFA]">영문 숫자 혼합 4~8자리</span>
          </div>
          <input
            type="text"
            name="referralCode"
            maxLength={8}
            required
            disabled={isLoading}
            value={formData.referralCode}
            onChange={handleChange}
            placeholder="예: GOODSHOP"
            className="w-full px-4 py-3 border border-[#E9E3FF] rounded-2xl focus:outline-none focus:ring-2 focus:ring-[#C084FC] focus:border-transparent transition-all placeholder:text-[#aaaaaa] tracking-wider font-mono disabled:bg-gray-50"
          />
        </div>

        {/* 개인정보 수집 및 이용 동의 체크박스 */}
        <div className="flex items-start gap-3 px-1 py-1 select-none">
          <input
            type="checkbox"
            id="privacyAgreement"
            disabled={isLoading}
            checked={isAgreed}
            onChange={(e) => setIsAgreed(e.target.checked)}
            className="w-5 h-5 rounded-md border-[#E9E3FF] text-[#7C3AED] focus:ring-[#C084FC] transition-all accent-[#7C3AED] mt-0.5 cursor-pointer disabled:opacity-50"
          />
          <label htmlFor="privacyAgreement" className="text-xs text-[#4C1D95] font-medium leading-relaxed cursor-pointer">
            <span className="text-[#8B5CF6] font-bold">[필수]</span> 개인정보 수집 및 이용 동의
            <p className="text-[#666666] font-normal text-[11px] mt-0.5">
              수집 목적: 인플루언서 리워드 정산 및 본인 확인<br />
              수집 항목: 이름, 연락처, SNS 채널 주소
            </p>
          </label>
        </div>

        {/* 에러 메시지 출력 */}
        {errorMessage && (
          <p className="text-xs font-medium text-red-500 px-1 -mt-2">{errorMessage}</p>
        )}

        {/* 안내 문구 */}
        <div className="bg-[#FAF5FF] rounded-2xl p-4 border border-[#F3E8FF] text-xs text-[#7C3AED] leading-relaxed">
          <p className="font-semibold mb-1">📢 필독 및 안내사항</p>
          <ul className="list-disc list-inside space-y-1 text-[#4817b9]">
            <li>제출하신 인플루언서 코드는 중복 검사 및 내부 검토 후 최종 승인됩니다.</li>
            <li>부적절한 단어나 타 브랜드를 사칭하는 코드는 반려될 수 있습니다.</li>
            <li>포인트 정산 및 내역 조사는 입력하신 이름과 연락처를 통해 진행됩니다.</li>
          </ul>
        </div>

        {/* 신청하기 버튼 */}
        <button
          type="submit"
          disabled={isLoading}
          className="w-full py-4 bg-[#7C3AED] hover:bg-[#6D28D9] text-white font-semibold rounded-2xl shadow-md transition-all active:scale-[0.98] mt-2 disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center"
        >
          {isLoading ? (
            <span className="animate-pulse">신청 처리 중...</span>
          ) : (
            '리워드 코드 신청하기'
          )}
        </button>
      </form>
    </div>
  );
}